name: limo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  file_picker: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
