// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9T-KDU9mlKewzZyBd19X3KKEfO_dKKE',
    appId: '1:256498985227:web:e82b3cf8ac70ef65731a0e',
    messagingSenderId: '256498985227',
    projectId: 'limo-9bdff',
    authDomain: 'limo-9bdff.firebaseapp.com',
    storageBucket: 'limo-9bdff.firebasestorage.app',
    measurementId: 'G-G6QBFGJ7N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOXisQiLcvQygI9070tfABl8xDnTqvIgs',
    appId: '1:256498985227:android:b41ffe87927086bc731a0e',
    messagingSenderId: '256498985227',
    projectId: 'limo-9bdff',
    storageBucket: 'limo-9bdff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChE3igXkSZK9M-1UVTTJLOrYPEVh7eixo',
    appId: '1:256498985227:ios:46281024c13e0bb2731a0e',
    messagingSenderId: '256498985227',
    projectId: 'limo-9bdff',
    storageBucket: 'limo-9bdff.firebasestorage.app',
    iosBundleId: 'com.example.limo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChE3igXkSZK9M-1UVTTJLOrYPEVh7eixo',
    appId: '1:256498985227:ios:46281024c13e0bb2731a0e',
    messagingSenderId: '256498985227',
    projectId: 'limo-9bdff',
    storageBucket: 'limo-9bdff.firebasestorage.app',
    iosBundleId: 'com.example.limo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD9T-KDU9mlKewzZyBd19X3KKEfO_dKKE',
    appId: '1:256498985227:web:4c52dea042064b31731a0e',
    messagingSenderId: '256498985227',
    projectId: 'limo-9bdff',
    authDomain: 'limo-9bdff.firebaseapp.com',
    storageBucket: 'limo-9bdff.firebasestorage.app',
    measurementId: 'G-FHNRYPCX4B',
  );

}